name: my_first_workflow
on:
    # push:
    #     branches:
    #         - main
    workflow_dispatch:

jobs:
    hello:
        runs-on: ubuntu-latest

        steps:
            - name: say hello
              run: echo "Hi from Pepu"
              
    bye:
        runs-on: ubuntu-latest
        needs: hello
        steps:
            - name: say bye
              run: echo "Bye from Pepu"
    # 