name: workflow_events
on:
    push:
        branches:
            - main
    workflow_dispatch:
jobs:
    events:
        runs-on: ubuntu-latest
        steps:
            - name: showing workflow event
              run: echo "The workflow is running on ${{ github.event }} event"
