name: workflow_events
on:
    push:
        branches:
            - main
    workflow_dispatch:
jobs:
    events:
        runs-on: ubuntu-latest
        steps:
            - name: showing workflow event
              run: echo "The workflow is running on a ${{ github.event_name }} event"
    
    conditonal:
        runs-on: ubuntu-latest
        needs: events
        if: ${{ github.event_name }} == "push" || ${{ github.workflow_runner }} != "ubuntu-latest"
        steps:
            - name: showing conditional event
              run: echo "The workflow is condition is true"