name: 14-Matrices

on:
  workflow_dispatch:
    inputs:
      use-cache:
        description: 'Use cache'
        type: boolean
        default: true

jobs:
  compatibility:
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Show Python version
        run: python --version

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Restore pip cache (if enabled)
        if: ${{ inputs.use-cache == true }}
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies (if requirements.txt exists)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found, skipping pip install."
          fi

      - name: Run build
        run: echo "✅ Build completed"
  
  check-bld-number:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: check build 
      run:  |
        echo "Build number is ${{ github.run_number }}"
        echo "Build id is ${{ github.run_id }}"