name: 15-Environments
run-name: 15-Environments | env - ${{ inputs.target-env }}

on:
  workflow_dispatch:
    inputs:
      target-env:
        description: "Target environment to deploy"
        type: environment
        default: staging

jobs:
  echo:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-env }}
    env:
      MY_SECRET_ENV_VAR: ${{ secrets.MY_SECRET_ENV_VAR }}

    steps:
      - name: Echo environment secret (masked)
        run: echo "Secret is set (but not displayed for security reasons)"
        
      - name: Confirm secret exists
        run: |
          if [ -z "$MY_SECRET_ENV_VAR" ]; then
            echo "❌ Secret is missing"
            exit 1
          else
            echo "✅ Secret is available"
          fi
