name: 15-Environments
run-name: 15-Environments | env - ${{ inputs.target-env }}

on:
  workflow_dispatch:
    inputs:
      target-env:
        description: "Target environment to deploy"
        type: environment
        default: prod

jobs:
  build:
    if: ${{ inputs.target-env == 'staging' }}
    runs-on: ubuntu-latest
    environment: staging
    env:
      MY_ENV_VALUE: ${{ vars.MY_ENV_VALUE }}
    steps:
      - name: Echo env var
        run: echo "Build Job - Env variable = $MY_ENV_VALUE"

  deploy:
    if: ${{ inputs.target-env == 'prod' }}
    runs-on: ubuntu-latest
    environment: prod
    env:
      MY_ENV_VALUE: ${{ vars.MY_ENV_VALUE }}
    steps:
      - name: Echo env var
        run: echo "Deploy Job - Env variable = $MY_ENV_VALUE"
