name: 15-Environments
run-name: 15-Environments | env - ${{ inputs.target-env }}

on:
  workflow_dispatch:
    inputs:
      target-env:
        description: "Target environment to deploy"
        type: environment
        default: prod

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs['target-env'] }}
    env:
      MY_ENV_VALUE: ${{ vars.MY_ENV_VALUE }} # This pulls from the environment's defined variables
    steps:
      - name: Echo env var
        run: echo "Env variable = $MY_ENV_VALUE"
        # 
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ inputs['target-env'] }}
    env:
      MY_ENV_VALUE: ${{ vars.MY_ENV_VALUE }} # This pulls from the environment's defined variables
    steps:
      - name: Echo env var
        run: echo "Env variable = $MY_ENV_VALUE"
        