name: 15-Environments
run-name: 15-Environments | env - ${{ inputs.target-env }}

on:
  workflow_dispatch:
    inputs:
      target-env:
        description: "Target environment to deploy"
        type: environment
        default: staging

jobs:
  echo:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-env }}
    env:
      my-env-value: ${{ vars.MY_ENV_VALUE }}

    steps:
      - name: Echo env variable
        run: echo "Env variable: $my-env-value"
